# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = """
╭$username\
$directory\
$git_branch\
$git_status\
$character"""

# username
[username]
show_always = true
format = "[$user](yellow): "


# directory
[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
format = "[$path](blue) "

# Git Branch
[git_branch]
format = "\\([$branch](purple)\\)"

# Git Status
[git_status]
disabled = false
staged = "[$count](green)"
untracked = "[…$count](blue)"
modified = "[+$count](yellow)"
deleted = "[✘$count](red)"
conflicted = ""
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
stashed = ""
renamed = ""
format = " $all_status"

# character
[character]
format = "\n╰─[❯](red)[❯](yellow)[❯](green) "


